import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "AI Flashcard",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<Navbar />
					<main>{children}</main>
				</body>
			</html>
		</ClerkProvider>
	);
}
